steps:

  # Install node packages
  - name: node:18
    entrypoint: npm
    args: [ 'install' ]
    dir: 'app'

  # Build productive files
  - name: node:18
    entrypoint: npm
    args: [ 'run', 'build-dev']
    dir: 'app'

  # Deploy to google cloud app egnine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'uat.yaml']
    dir: 'app'

options:
 logging: CLOUD_LOGGING_ONLY
