steps:

  # Install node packages
  - name: node
    entrypoint: npm
    args: [ 'install' ]
    dir: 'app'

  # Build productive files
  - name: node
    entrypoint: npm
    args: [ 'run', 'build', '-c', 'production' ] 
    dir: 'app'

  # Deploy to google cloud app egnine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'prod.yaml']
    dir: 'app'
    
options:
 logging: CLOUD_LOGGING_ONLY