runtime: python27
api_version: 1
threadsafe: true

skip_files:
- node_modules/
- .angular/
- e2e/
- src/

handlers:
# index files
- url: /([^.]+)/?$  # urls with no dot in them
  static_files: dist/paper-mario-randomizer-app/index.html
  upload: dist/index.html

# site root
- url: /
  static_files: dist/paper-mario-randomizer-app/index.html
  upload: dist/paper-mario-randomizer-app/index.html

# everything else
- url: /(.*)
  static_files: dist/paper-mario-randomizer-app/\1
  upload: dist/paper-mario-randomizer-app/(.*)
  
automatic_scaling:
  max_instances: 4